// Generated by tools/gen-levels.js — do not edit by hand.
window.MIX_LEVELS = [
 {
  "name": "Le ballon",
  "hint": "Touche un pot, puis un bol. Le bol peint tout seul les pixels de sa couleur.",
  "picture": [
   "..RRR..",
   ".RRRRR.",
   ".RRRRR.",
   ".RRRRR.",
   "..RRR..",
   "...R...",
   "...B...",
   "..B....",
   "...B..."
  ],
  "bowls": 3,
  "cap": 12,
  "cols": [
   [
    {
     "c": "R",
     "n": 6
    }
   ],
   [
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "R",
     "n": 6
    },
    {
     "c": "R",
     "n": 6
    },
    {
     "c": "R",
     "n": 4
    }
   ]
  ]
 },
 {
  "name": "La feuille",
  "hint": "Jaune + Bleu = Vert ! Mets les deux pots dans le même bol.",
  "picture": [
   "......GG",
   "....GGGG",
   "..GGGGGG",
   ".GGGGGG.",
   "GGGGGG..",
   "GGGGG...",
   ".GGG....",
   "G......."
  ],
  "bowls": 3,
  "cap": 12,
  "cols": [
   [
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "Y",
     "n": 6
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "Y",
     "n": 2
    }
   ],
   [
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "Y",
     "n": 3
    },
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "Y",
     "n": 4
    }
   ]
  ]
 },
 {
  "name": "L'orange",
  "hint": "Rouge + Jaune = Orange. Attention : les trois couleurs ensemble font de la boue.",
  "picture": [
   "....GG..",
   "...GG...",
   "..OOOO..",
   ".OOOOOO.",
   "OOOOOOOO",
   "OOOOOOOO",
   ".OOOOOO.",
   "..OOOO.."
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "Y",
     "n": 3
    }
   ],
   [
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "Y",
     "n": 2
    }
   ],
   [
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "Y",
     "n": 2
    },
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "Y",
     "n": 2
    },
    {
     "c": "Y",
     "n": 2
    }
   ]
  ]
 },
 {
  "name": "Le raisin",
  "hint": "Rouge + Bleu = Violet. Un bol rempli d’une couleur inutile reste bloqué.",
  "picture": [
   "....GG..",
   "...GG...",
   "..VV.VV.",
   ".VVVVVVV",
   "..VVVVV.",
   ".VVV.VV.",
   "..VVVV..",
   "...VV...",
   "....V..."
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "B",
     "n": 3
    }
   ],
   [
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "R",
     "n": 2
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 3
    }
   ],
   [
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "R",
     "n": 2
    },
    {
     "c": "Y",
     "n": 1
    },
    {
     "c": "R",
     "n": 6
    }
   ]
  ]
 },
 {
  "name": "La tulipe",
  "hint": "L’ordre compte ! Un bol qui peut peindre peint tout de suite. Pour l’orange, pose le jaune en premier.",
  "picture": [
   ".R.R.R.",
   ".RRORR.",
   ".RROOR.",
   ".RRORR.",
   "..RRR..",
   "...G...",
   ".G.G.G.",
   "..GGG..",
   "...G..."
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "R",
     "n": 3
    }
   ],
   [
    {
     "c": "R",
     "n": 3
    }
   ],
   [
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "Y",
     "n": 1
    }
   ]
  ]
 },
 {
  "name": "Coucher de soleil",
  "hint": "Ici le jaune sert seul : pour l’orange, commence par le rouge.",
  "picture": [
   "...YYYY...",
   "..YYYYYY..",
   ".OYYYYYYO.",
   "OOOOOOOOOO",
   "BBBBBBBBBB",
   ".BBBBBBBB.",
   "BBBBBBBBBB"
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "R",
     "n": 6
    },
    {
     "c": "B",
     "n": 6
    },
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "B",
     "n": 5
    }
   ],
   [
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "Y",
     "n": 3
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "B",
     "n": 4
    }
   ],
   [
    {
     "c": "Y",
     "n": 4
    },
    {
     "c": "Y",
     "n": 4
    },
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "Y",
     "n": 2
    },
    {
     "c": "Y",
     "n": 1
    }
   ]
  ]
 },
 {
  "name": "Le papillon",
  "hint": "Des pots en trop peuvent bloquer ton chemin. Garde un bol « poubelle » si besoin.",
  "picture": [
   "VV.....VV",
   "VVV...VVV",
   "VOVV.VVOV",
   "VVVVBVVVV",
   ".VVVBVVV.",
   "..VVBVV..",
   ".VOVBVOV.",
   "VVVV.VVVV",
   ".VV...VV."
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "Y",
     "n": 1
    },
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "B",
     "n": 1
    }
   ],
   [
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "R",
     "n": 2
    },
    {
     "c": "B",
     "n": 1
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "R",
     "n": 2
    },
    {
     "c": "R",
     "n": 4
    }
   ],
   [
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "R",
     "n": 3
    }
   ],
   [
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "R",
     "n": 3
    }
   ]
  ]
 },
 {
  "name": "Le perroquet",
  "hint": "Nouveau : les pots mystère « ? » révèlent leur couleur quand ils arrivent devant.",
  "picture": [
   "...RRR...",
   "..RRRRR..",
   "..RYRRRR.",
   "..RRRRYY.",
   "..RRRR.Y.",
   "...GGG...",
   "..GGGGG..",
   "..BGGGB..",
   "..BBGBB..",
   "...B.B..."
  ],
  "bowls": 4,
  "cap": 12,
  "cols": [
   [
    {
     "c": "R",
     "n": 3
    }
   ],
   [
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "Y",
     "n": 4
    },
    {
     "c": "R",
     "n": 6
    },
    {
     "c": "R",
     "n": 4
    }
   ],
   [
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "Y",
     "n": 2,
     "hidden": true
    }
   ],
   [
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "B",
     "n": 3,
     "hidden": true
    },
    {
     "c": "B",
     "n": 3,
     "hidden": true
    },
    {
     "c": "Y",
     "n": 3,
     "hidden": true
    }
   ]
  ]
 },
 {
  "name": "L'arc-en-ciel",
  "hint": "Nouveau : les pots gelés dégèlent après quelques coups. Six couleurs à faire !",
  "picture": [
   "..RRRRRR..",
   ".ROOOOOOR.",
   "ROYYYYYYOR",
   "OYGGGGGGYO",
   "YGBBBBBBGY",
   "GBVV..VVBG",
   "BV......VB",
   "V........V"
  ],
  "bowls": 5,
  "cap": 12,
  "cols": [
   [
    {
     "c": "Y",
     "n": 3,
     "ice": 3
    },
    {
     "c": "Y",
     "n": 4
    },
    {
     "c": "Y",
     "n": 2
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "R",
     "n": 2
    }
   ],
   [
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "Y",
     "n": 2
    },
    {
     "c": "R",
     "n": 4,
     "ice": 15
    },
    {
     "c": "R",
     "n": 6
    }
   ],
   [
    {
     "c": "Y",
     "n": 6
    },
    {
     "c": "B",
     "n": 2
    },
    {
     "c": "B",
     "n": 6
    }
   ],
   [
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "R",
     "n": 4
    },
    {
     "c": "Y",
     "n": 5
    },
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "B",
     "n": 4,
     "ice": 13
    },
    {
     "c": "B",
     "n": 2
    }
   ]
  ]
 },
 {
  "name": "La nuit étoilée",
  "hint": "Chef-d’œuvre final, d’après Van Gogh. Prends ton temps.",
  "picture": [
   "BBBBBBBYYB",
   "BYBBVBBYOY",
   "BBBVVVBBOB",
   "BBVBBBVBBB",
   "YBBBBBBBVB",
   "BBVVBBBVBB",
   "GGBBBYBBBB",
   "GGGBBBBBBV",
   "GGGVVVVVVV",
   "GGGGVVVVVV"
  ],
  "bowls": 5,
  "cap": 12,
  "cols": [
   [
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "B",
     "n": 5
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "Y",
     "n": 1
    },
    {
     "c": "B",
     "n": 5,
     "ice": 26
    },
    {
     "c": "B",
     "n": 4
    }
   ],
   [
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "Y",
     "n": 4
    },
    {
     "c": "R",
     "n": 2
    },
    {
     "c": "B",
     "n": 3,
     "hidden": true
    },
    {
     "c": "R",
     "n": 3
    },
    {
     "c": "Y",
     "n": 5,
     "hidden": true
    },
    {
     "c": "B",
     "n": 6
    }
   ],
   [
    {
     "c": "Y",
     "n": 3
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "R",
     "n": 1,
     "hidden": true
    },
    {
     "c": "B",
     "n": 5,
     "hidden": true
    },
    {
     "c": "R",
     "n": 3,
     "hidden": true,
     "ice": 19
    },
    {
     "c": "Y",
     "n": 1
    },
    {
     "c": "B",
     "n": 3,
     "hidden": true
    }
   ],
   [
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 5,
     "hidden": true
    },
    {
     "c": "Y",
     "n": 4,
     "ice": 14
    },
    {
     "c": "B",
     "n": 1
    },
    {
     "c": "B",
     "n": 4
    },
    {
     "c": "B",
     "n": 3
    },
    {
     "c": "B",
     "n": 3
    }
   ],
   [
    {
     "c": "R",
     "n": 5
    },
    {
     "c": "B",
     "n": 3,
     "hidden": true
    },
    {
     "c": "B",
     "n": 3
    }
   ]
  ]
 }
];
